// frontends/angular/src/app/keyboard/keyboard.component.ts
import { Component, Input, OnInit, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-keyboard',
  templateUrl: './keyboard.component.html',
  styleUrls: ['./keyboard.component.css'],
})
export class KeyboardComponent implements OnInit {
  @Input() kind: number = 0;
  @Input() type: string = '';
  @Input() filter: string = '';
  @Input() owner: string = '';
  @Input() preview: boolean = false;

  public alt: string = '';
  public imagePath: string = '';
  public style: string = '';
  public connectedAccount: string = <string>localStorage.getItem('metamask');

  constructor() {}

  ngOnInit(): void {
    this.displayImage();
  }

  displayImage() {
    const kindDir = this.getKindDir(this.kind);
    const filename = this.type;
    this.imagePath = `assets/keyboards/${kindDir}/${filename}.png`;
    this.alt = `${kindDir} keyboard with ${filename} keys ${
      this.filter
        ? `with
${this.filter}`
        : ''
    }`;
    this.style = this.filter;
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['kind']) {
      this.kind = changes['kind'].currentValue;
    }
    if (changes['type']) {
      this.type = changes['type'].currentValue;
    }
    if (changes['filter']) {
      this.filter = changes['filter'].currentValue;
    }
    this.displayImage();
  }

  getKindDir(kind: number) {
    return {
      0: 'sixty-percent',
      1: 'seventy-five-percent',
      2: 'eighty-percent',
      3: 'iso-105',
    }[kind];
  }

  addressesEqual(addr1: string, addr2: string) {
    if (!addr1 || !addr2) return false;
    return addr1.toUpperCase() === addr2.toUpperCase();
  }
}

<h2 *ngIf="preview">Preview</h2>
<div class="borders">
	<img [height]="230" [width]="360" [class]="filter" [src]="imagePath" [alt]="alt" />
</div>
<span *ngIf="!preview && !isTipping">
	<button *ngIf="!(owner | addressesEqual: currentOwner)" class="btn btn-tip" (click)="tip()">Tip</button>
	<button *ngIf="owner | addressesEqual: currentOwner" class="btn btn-no-tip">You own it!</button>
</span>

<span *ngIf="!preview && isTipping">
	<button *ngIf="!(owner | addressesEqual: currentOwner)" class="btn btn-tip">Tipping 0.1 ETH...</button>
</span>

// frontends/react-app/src/components/Keyboard.js
import { useEffect, useState } from 'react';

export default function Keyboard({ keyboard, preview }) {
  const [alt, setAlt] = useState('');
  const [imagePath, setImagePath] = useState('');
  const [style, setStyle] = useState('');
  const [connectedAccount, setConnectedAccount] = useState('');
  const [isOwner, setIsOwner] = useState(false);

  useEffect(() => {
    displayImage();
  }, [keyboard]);

  useEffect(() => {
    if (localStorage.getItem('metamask')) {
      setConnectedAccount(localStorage.getItem('metamask'));

      if (connectedAccount === keyboard.ownerAddress) {
        setIsOwner(true);
      }
    }
  }, [connectedAccount, keyboard.ownerAddress]);

  function getKindDir(kind) {
    return {
      0: 'sixty-percent',
      1: 'seventy-five-percent',
      2: 'eighty-percent',
      3: 'iso-105',
    }[kind];
  }

  function displayImage() {
    const kindDir = getKindDir(keyboard.keyboardKind);
    const filename = keyboard.keyboardType.toUpperCase();
    setImagePath(`assets/keyboards/${kindDir}/${filename}.png`);
    setAlt(
      `${kindDir} keyboard with ${filename} keys ${
        keyboard.keyboardFilter
          ? `with
${keyboard.keyboardFilter}`
          : ''
      }`
    );
    setStyle(keyboard.keyboardFilter);
  }

  return (
    <div className="nft">
      {preview && <h2>Preview</h2>}
      <div className="borders">
        <img
          height={230}
          width={360}
          className={style}
          src={imagePath}
          alt={alt}
        />
      </div>
      {!preview && !isOwner && <button className="btn btn-tip">Tip</button>}
      {!preview && isOwner && (
        <button className="btn btn-no-tip">You own it!</button>
      )}
    </div>
  );
  //   return <>

  // <span *ngIf="!preview">
  //   <button
  //     *ngIf="!(owner | addressesEqual: connectedAccount)"
  //     className="btn btn-tip"
  //   >
  //     Tip
  //   </button>
  //   <button
  //     *ngIf="owner | addressesEqual: connectedAccount"
  //     className="btn btn-no-tip"
  //   >
  //     You own it!
  //   </button>
  // </span>
  // </>;
}
