// frontends/angular/src/app/create-nft/create-nft.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, Input, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormGroupName,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';

const API_URL = 'http://localhost:5000';

@Component({
  selector: 'app-create-nft',
  templateUrl: './create-nft.component.html',
  styleUrls: ['./create-nft.component.css'],
})
export class CreateNftComponent implements OnInit {
  public form: FormGroup | any;
  public success: boolean = false;
  public error: boolean = false;

  public owner: string = <string>localStorage.getItem('metamask');

  constructor(
    private _fb: FormBuilder,
    private _httpClient: HttpClient,
    private _router: Router
  ) {
    this.initializeForm();
  }

  ngOnInit(): void {}

  private initializeForm() {
    this.form = this._fb.group({
      keyboardKind: ['0', Validators.required],
      keyboardType: ['abs', Validators.required],
      keyboardFilter: ['none', Validators.required],
      ownerAddress: [this.owner, Validators.required],
    });
  }

  onSubmit() {
    const nftObj = {
      kind: this.form.get('keyboardKind').value,
      type: this.form.get('keyboardType').value,
      filter: this.form.get('keyboardFilter').value,
      owner: this.form.get('ownerAddress').value,
    };
    this._httpClient.post(`${API_URL}/nft`, nftObj).subscribe(
      (result: any) => {
        console.log('Result:::', result);
        if (result.success) {
          this._router.navigate(['']);
        }
      },
      (error: any) => {
        console.error('Error in Creation:::', error.error);
        if (!error.error.success) {
          alert(error.error.message);
        }
      }
    );
  }
}

<form class="form" [formGroup]="form" (submit)="onSubmit()">
  <div class="form-group">
    <label for="kind">Keyboard Kind</label>
    <select id="kind" formControlName="keyboardKind">
      <option value="0">60%</option>
      <option value="1">75%</option>
      <option value="2">80%</option>
      <option value="3">ISO-105</option>
    </select>
  </div>
  <div class="form-group">
    <label for="type">Keyboard Type</label>
    <select id="type" formControlName="keyboardType">
      <option value="abs">ABS</option>
      <option value="pbt">PBT</option>
    </select>
  </div>
  <div class="form-group">
    <label for="filter">Keyboard Filter</label>
    <select id="filter" formControlName="keyboardFilter">
      <option value="none">None</option>
      <option value="sepia">Sepia</option>
      <option value="grayscale">Grayscale</option>
      <option value="invert">Invert</option>
      <option value="hue-rotate-90">Hue Rotate (90°)</option>
      <option value="hue-rotate-180">Hue Rotate (180°)</option>
    </select>
  </div>
  <button type="submit" class="btn btn-black">Mint NFT</button>
</form>

<section class="preview">
  <app-keyboard
    [kind]="form.get('keyboardKind').value"
    [type]="form.get('keyboardType').value | uppercase"
    [filter]="form.get('keyboardFilter').value"
    [owner]="form.get('ownerAddress').value"
    [preview]="true"
  ></app-keyboard>
</section>

// frontends/react-app/src/CreateNFT.js
import { useEffect, useState } from 'react';
import axios from 'axios';
import Keyboard from './components/Keyboard';

const API_URL = 'http://localhost:5000';

export function CreateNFT() {
  const [keyboard, setKeyboard] = useState({
    keyboardKind: 0,
    keyboardType: 'pbt',
    keyboardFilter: 'none',
    ownerAddress: '',
  });

  useEffect(() => {
    setKeyboard({
      ...keyboard,
      ownerAddress: localStorage.getItem('metamask'),
    });
  }, []);

  function change(event) {
    setKeyboard({ ...keyboard, [event.target.name]: event.target.value });
  }

  async function onSubmit(event) {
    event.preventDefault();
    const nft = {
      kind: keyboard.keyboardKind,
      type: keyboard.keyboardType,
      filter: keyboard.keyboardFilter,
      owner: keyboard.ownerAddress,
    };
    console.log(nft);
    const { data } = await axios.post(`${API_URL}/nft`, nft);
    if (data.success) {
      notify(data.message);
      window.location.href = '/';
    }
  }

  function notify(message) {
    alert(message);
  }

  return (
    <>
      <form className="form" onSubmit={onSubmit}>
        <div className="form-group">
          <label htmlFor="kind">Keyboard Kind</label>
          <select
            id="kind"
            name="keyboardKind"
            onChange={change}
            defaultValue={keyboard.keyboardKind}
          >
            <option value="0">60%</option>
            <option value="1">75%</option>
            <option value="2">80%</option>
            <option value="3">ISO-105</option>
          </select>
        </div>
        <div className="form-group">
          <label htmlFor="type">Keyboard Type</label>
          <select
            id="type"
            name="keyboardType"
            onChange={change}
            defaultValue={keyboard.keyboardType}
          >
            <option value="abs">ABS</option>
            <option value="pbt">PBT</option>
          </select>
        </div>
        <div className="form-group">
          <label htmlFor="filter">Keyboard Filter</label>
          <select
            id="filter"
            name="keyboardFilter"
            onChange={change}
            defaultValue={keyboard.keyboardFilter}
          >
            <option value="none">None</option>
            <option value="sepia">Sepia</option>
            <option value="grayscale">Grayscale</option>
            <option value="invert">Invert</option>
            <option value="hue-rotate-90">Hue Rotate (90°)</option>
            <option value="hue-rotate-180">Hue Rotate (180°)</option>
          </select>
        </div>
        <button type="submit" className="btn btn-black">
          Mint NFT
        </button>
      </form>

      <section className="preview">
        <Keyboard preview={true} keyboard={keyboard} />
      </section>
    </>
  );
}
